#k8s/00-namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: kates-closetx
  labels:
    team: kates
    project: closet-x
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: kates-closetx-quota
  namespace: kates-closetx
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 20Gi
    requests.storage: 50Gi
    persistentvolumeclaims: "5"
    pods: "30"
    services: "10"
