#k8s/08-image-processor.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-processor
  namespace: kates-closetx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-processor
  template:
    metadata:
      labels:
        app: image-processor
    spec:
      imagePullSecrets:
      - name: harbor-secret
      containers:
      - name: image-processor
        image: harbor.javajon.duckdns.org/library/image-processor:v9.0.0
        env:
        - name: NODE_ENV
          value: "production"
        - name: MONGO_URI
          value: "mongodb://wardrobe_service:service_password_123@mongodb-service.kates-closetx.svc.cluster.local:27017/closetx_wardrobe?authSource=admin"
        - name: RABBITMQ_URL
          value: "amqp://admin:admin@rabbitmq.rabbitmq.svc.cluster.local:5672"
        - name: WARDROBE_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: closetx-config
              key: WARDROBE_SERVICE_URL
        - name: REMOVEBG_API_KEY
          valueFrom:
            secretKeyRef:
              name: closetx-secrets
              key: REMOVEBG_API_KEY
        - name: GOOGLE_VISION_API_KEY
          valueFrom:
            secretKeyRef:
              name: closetx-secrets
              key: GOOGLE_VISION_API_KEY
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"