# k8s/services/wardrobe-service/service.yaml

apiVersion: v1
kind: Service
metadata:
  name: wardrobe-service
  namespace: closet-x
  labels:
    app: wardrobe-service
    tier: backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3002"
spec:
  type: ClusterIP
  selector:
    app: wardrobe-service
  ports:
  - name: http
    port: 80
    targetPort: 3002
    protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800